"""Update models to match schema

Revision ID: 07274ccba8a2
Revises: a809be99795f
Create Date: 2024-11-07 21:32:33.041290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07274ccba8a2'
down_revision = 'a809be99795f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
