"""Initial migration.

Revision ID: 197359e36a28
Revises: 
Create Date: 2024-08-30 10:10:57.458713

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '197359e36a28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('message', schema=None) as batch_op:
            batch_op.add_column(sa.Column('addr_h', sa.String(length=100), nullable=False))
            batch_op.add_column(sa.Column('data_h', sa.String(length=100), nullable=False))
    except:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('data_h')
        batch_op.drop_column('addr_h')

    # ### end Alembic commands ###
