"""Update models to match schema

Revision ID: 58364eab5742
Revises: 07274ccba8a2
Create Date: 2024-11-07 21:35:09.881982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58364eab5742'
down_revision = '07274ccba8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
