"""hello

Revision ID: a809be99795f
Revises: cf7042781ee9
Create Date: 2024-11-07 21:17:40.957920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a809be99795f'
down_revision = 'cf7042781ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('machine')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.INTEGER(), nullable=True))

    op.create_table('machine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('machine_id', sa.INTEGER(), nullable=True),
    sa.Column('pda_id', sa.INTEGER(), nullable=True),
    sa.Column('employee', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
