"""Allow NULL values for addr_h, addr_l, data_h, data_l

Revision ID: cf7042781ee9
Revises: 197359e36a28
Create Date: 2024-08-30 11:21:04.947198

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cf7042781ee9'
down_revision = '197359e36a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('addr_l',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=True)
        batch_op.alter_column('addr_h',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=True)
        batch_op.alter_column('data_l',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=True)
        batch_op.alter_column('data_h',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('data_h',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=False)
        batch_op.alter_column('data_l',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=False)
        batch_op.alter_column('addr_h',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=False)
        batch_op.alter_column('addr_l',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=False)

    # ### end Alembic commands ###
